package com.example.telecompdf;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.util.List;

@RestController
public class UsagePdfController {

    private final UsageRepo repo;
    public UsagePdfController(UsageRepo repo) { this.repo = repo; }

    @GetMapping("/usage/pdf")
    public ResponseEntity<byte[]> downloadPdf() throws DocumentException {
        List<Usage> rows = repo.findAll();

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4, 50, 50, 50, 50);
        PdfWriter.getInstance(doc, out);
        doc.open();

        // 🔹 Company/Invoice Title
        Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, Color.BLUE);
        Paragraph title = new Paragraph("Telecom Billing Invoice", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);

        doc.add(new Paragraph("Date: " + LocalDate.now()));
        doc.add(new Paragraph("Generated by: Telecom Billing System"));
        doc.add(Chunk.NEWLINE);

        // 🔹 Create Table with Header
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        table.setSpacingAfter(10f);

        Font headerFont = new Font(Font.HELVETICA, 12, Font.BOLD, Color.WHITE);

        PdfPCell h1 = new PdfPCell(new Phrase("ID", headerFont));
        PdfPCell h2 = new PdfPCell(new Phrase("MSISDN", headerFont));
        PdfPCell h3 = new PdfPCell(new Phrase("Plan", headerFont));
        PdfPCell h4 = new PdfPCell(new Phrase("Amount Due", headerFont));

        h1.setBackgroundColor(Color.DARK_GRAY);
        h2.setBackgroundColor(Color.DARK_GRAY);
        h3.setBackgroundColor(Color.DARK_GRAY);
        h4.setBackgroundColor(Color.DARK_GRAY);

        table.addCell(h1);
        table.addCell(h2);
        table.addCell(h3);
        table.addCell(h4);

        // 🔹 Add Rows from DB
        for (Usage u : rows) {
            table.addCell(String.valueOf(u.getId()));
            table.addCell(u.getMsisdn());
            table.addCell(u.getPlan() == null ? "" : u.getPlan());
            table.addCell(u.getAmountDue() == null ? "" : "₹" + u.getAmountDue().toString());
        }

        doc.add(table);

        // 🔹 Footer Note
        Paragraph footer = new Paragraph("This is a system-generated invoice. For queries, contact support@telecom.com",
                new Font(Font.HELVETICA, 10, Font.ITALIC, Color.GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        doc.add(footer);

        doc.close();

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=invoice.pdf")
                .contentType(MediaType.APPLICATION_PDF)
                .body(out.toByteArray());
    }
}
